version: '3.8'
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models
  geth:
    image: ethereum/client-go
    command: --http --dev
    ports:
      - "8545:8545"
  grok-doc:
    build: .
    depends_on:
      - triton
      - geth
    ports:
      - "5000:5000"
